version: "3.6"

services:
  # db-app:
  #   image: mysql
  #   container_name: db-app
  #   ports:
  #     - 3308:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1234
  #     MYSQL_DATABASE: david

  # phpmyadmin:
  #   image: phpmyadmin
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: db-app
  #     PMA_ARBITRARY: 1
  #   links:
  #     - db-app

  api-express:
    build: .
    container_name: api-express
    ports:
      - 4000:4000
    volumes:
      - ./:/app
      - nodeModules:/node_modules

volumes:
  nodeModules:
